### ISSUE TITLE
Attached blank page as a screen-shot

### ISSUE THREAD

**Issue by shivanthalakmal** [allure-framework/allure-jasmine#22] opened 2017-03-22 11:13 UTC
![image](https://cloud.githubusercontent.com/assets/7554175/24195074/5ca4bc2c-0f1e-11e7-8d06-92f91ebd618c.png)

--------------------------------------------
![image](https://cloud.githubusercontent.com/assets/7554175/24195154/b138b32e-0f1e-11e7-9e56-9d344c9eab48.png)

Please let me know what is configured wrong.
Appreciate your help.

**Comment by baev** [comment] 2017-03-22 11:13
Are you using IE11 ?

**Comment by shivanthalakmal** [comment] 2017-03-22 11:15
For execution used chrome. and to view report using firefox

**Comment by baev** [comment] 2017-03-22 11:17
Any erros in browser console?

**Comment by shivanthalakmal** [comment] 2017-03-22 11:18
![image](https://cloud.githubusercontent.com/assets/7554175/24195277/2c3955d8-0f1f-11e7-84dd-08bbd254966a.png)

i have missed in previous comment to call 'done()' method because it gives error like this any reason for that

**Comment by shivanthalakmal** [comment] 2017-03-23 04:52
@just-boris @baev @ctapobep 
Any update on this ? 
Is necessary to apply 'done()' callback method

**Comment by just-boris** [comment] 2017-03-23 09:18
Hello, @shivanthalakmal 
The problem, that you are facing can be caused by a lot of reasons, not necessarily related to Allure.
Here is a short list of questions, that may help you to find out a reason
1. Do you have an image in `allure-results` folder, what does it content?
2. Have you tried to make a screenshot without Allure. Does it change anything?
3. And last, but not least, what do you expect to see in the image. Are you sure, that you have opened the page and waited until it has been fully loaded?

**Comment by shivanthalakmal** [comment] 2017-03-28 10:18
Hi, @just-boris ,
i went through the criteria you have shared and i were able to found the root cause,
problem was , 
"restartBrowserBetweenTests: true,"
in protractor.config.js file screenshot generated as blank page. when its change as 'false' its working as expected way. any reason for that ?

**Comment by just-boris** [comment] 2017-03-28 10:26
This is probably related to https://github.com/angular/protractor/issues/2946

Then I close this one, as no-action to Allure reporter.

**Closed by just-boris** 2017-03-28 10:26 UTC
